NOMBRES_POR_EMAIL = {
    "abellidoluque@gmail.com": "Cheli Alumna",
    "acarmonaramos@gmail.com": "Antonio Carmona Alumno",
    "adrian-rey@hotmail.es": "adrian alumno",
    "adrian.millan.garcia@hotmail.com": "Adrian Millan Alumno",
    "agu700@hotmail.es": "Agustin Alumno",
    "ajim22@gmail.com": "Antuan Jimenez Alumno",
    "alemaclop@gmail.com": "Alejandro Macias Alumno",
    "alsopberet@gmail.com": "Jonatan Alumno",
    "angel66lr@gmail.com": "Angel Alumno",
    "antoniojosemarquez@yahoo.es": "antonio alumno",
    "antoniomiguel1992@hotmail.com": "antonio miguel alumno",
    "antonioxperias55@gmail.com": "Juan Nuñez Alumno",
    "bdeliba@gmail.com": "Borja del Cura Alumno",
    "bgonlun@gmail.com": "Borja González Alumno",
    "bonevoisage.vm_36@hotmail.com": "Victor M. Rubio Alumno",
    "calahorgy@hotmail.com": "cala",
    "calicator@gmail.com": "David Mendoza Alumno",
    "cam.hanekan@gmail.com": "Cam Alumno",
    "celia.jeje@yahoo.es": "Celia Alumna",
    "cerveceriana@hotmail.com": "fernando jimenez aguilar",
    "chussosalas@gmail.com": "Antonio salas Alumno",
    "cjprideaux10@gmail.com": "Jason Alumno",
    "cvargas_22@hotmail.com": "Cristobal alumno",
    "danidelfin70@gmail.com": "Dani Villa",
    "daniellm2007@hotmail.com": "Dani GhostSlayer Alumno",
    "danielvillaa70@gmail.com": "Dani Villa Alumno",
    "david.aulaelectrica@gmail.com": "David Mendoza Alumno",
    "davidrtecnologia@gmail.com": "David Rayo Alumno",
    "dh_maurin@yahoo.es": "David Hernandez Alumno",
    "diegogijongordillo@gmail.com": "Diego Gijon Alumno",
    "el_piernaslocas@hotmail.com": "eloy alumno",
    "emirlio@hotmail.com": "Emilio Alumno",
    "emldeni@hotmail.com": "Emilio Muñoz Alumno",
    "enriddick09@hotmail.com": "Quique Alumno",
    "escarabajokillo@gmail.com": "Jose Luis Ruiz Alumno",
    "fcojaviermartinezjimenez@gmail.com": "Javier Martinez Alumno",
    "fede_rouge90@hotmail.com": "fede alumno",
    "fernan_xs@hotmail.com": "Fernando Jimenez Alumno",
    "fernandezgutierrezdavid@gmail.com": "David Fernandez Gutierrez Alumno",
    "francisco.j.baeza@gmail.com": "francisco baeza Alumno",
    "frankyhill@hotmail.com": "Javier Alumno",
    "garridocaro@ono.com": "Jose Luis Alumno",
    "hi.pablo.alvarez@gmail.com": "Pablo Alvarez Alumno",
    "hipolitosuarez0@gmail.com": "Hipolito Alumno",
    "hmofford@live.com": "Helen Alumna",
    "igarmar2402b@g.educaand.es": "Ivan Garcia Alumno",
    "ignacio_roncero@yahoo.es": "Nacho alumno",
    "ilm41@hotmail.com": "Israel Lopez Alumno",
    "ilmmacareno@gmail.com": "Israel Lopez Alumno",
    "iloveyoupichon@hotmail.com": "Toñy",
    "isaac.ipt@gmail.com": "Isaac Alumno",
    "ja_p_gomez@hotmail.com": "jose antonio alumno",
    "jcasanuevam@hotmail.com": "Javier Casanueva Alumno",
    "jcdmp.97@gmail.com": "Juan Carlos Alumno",
    "jdgarciaramos@gmail.com": "Jose David Alumno",
    "jeison.-@hotmail.com": "Jeison Alumno",
    "jhon_rhcp@hotmail.com": "Juan Alumno",
    "jlgarrido@sodinur.com": "jose luis garrido",
    "jmcito83@hotmail.com": "Jose Manuel Benitez Alumno",
    "josanrodmar@yahoo.es": "Jose Andres Alumno",
    "josbenrub@gmail.com": "Jose Maria Benitez Alumno",
    "joseantoniolopezortega@yahoo.es": "Chico Alumno",
    "joseglamrock@gmail.com": "Jose glamrock Alumno",
    "joselurudu@gmail.com": "Jose Luis Ruiz Alumno",
    "joshuatree82@hotmail.com": "Jose Maria ron",
    "jrk_74@hotmail.com": "Pepe Requerey Alumno",
    "juanalberto1978@yahoo.es": "Juan A. Navarro Alumno",
    "juanantonio_calero@hotmail.com": "Juan Calero Alumno",
    "juancarlos.miguelgarcia@telefonica.net": "Juan carlos alumno",
    "juanmadoji@gmail.com": "juanma alumno",
    "juanreztana@gmail.com": "Juan Ramirez Alumno",
    "juansece95@gmail.com": "Juan Sanchez Alumno",
    "kiwisuperpower@hotmail.com": "Dani Gamez Alumno",
    "lgaliano.lg@gmail.com": "Luis Galiano Alumno",
    "lnz.marinelli@gmail.com": "Lorenzo Marinelli",
    "lucasdiegoarredondo@gmail.com": "Lucas Arredondo Alumno",
    "luiis0940@gmail.com": "Luis Diaz Alumno",
    "luiis0940@hotmail.com": "Luis Diaz Alumno",
    "luis.galloso@gmail.com": "Luis Galloso Alumno",
    "luistrigoacosta@gmail.com": "Luis Trigo Alumno",
    "maaanuel@yahoo.es": "Maaanuel Garcia Alumno",
    "manuelcalvo1973@gmail.com": "Manuel Calvo Alumno",
    "manuelcalvo@estudiomc.es": "Manuel Calvo Alumno",
    "manuelgarciamateos@hotmail.com": "Manuel Mateos Alumno",
    "maxkemper@hotmail.com": "Max Alumno",
    "mercedespimiento@hotmail.com": "Mercedes Alumna",
    "miguel.murillo@reale.es": "Miguel Murillo Alumno",
    "miguelgil24@yahoo.es": "miguel alumno",
    "miguelmuradpuchol9@gmail.com": "Miguel Murad Alumno",
    "miraslade@hotmail.com": "Joaquin Slade Alumno",
    "mmiguell5@hotmail.com": "Miguel Alvarez Alumno",
    "nmaferrero@gmail.com": "Inma Alumna",
    "nonete2005@gmail.com": "Nonete Alumno",
    "nono574@hotmail.com": "antonio martinez mateo",
    "nonomotero@gmail.com": "Nono Alumno",
    "ojolobo1@gmail.com": "Alex Alumno",
    "otomiguel@hotmail.es": "Miguel Alberto",
    "paulaamieva_09@hotmail.com": "Paula Alumna",
    "paulatrigovalero2001@gmail.com": "Paula Trigo Alumna",
    "paulatrigovalero@gmail.com": "Paula Trigo Alumna",
    "pedmuitor@gmail.com": "Pedro Muiños Alumno",
    "pedroauxi@telefonica.net": "Pedro Guanche Alumno",
    "pepe25100@hotmail.com": "pepe alumno",
    "pepeberro@gmail.com": "Pepe Berro Alumno",
    "pepeglez1@yahoo.es": "Pepe Gonzalez Alumno",
    "petrer_sevillista@hotmail.com": "Juan carlos alumno",
    "pferni@gmail.com": "fernando alumno",
    "plesa_ady@yahoo.com": "Adrian Plesa Alumno",
    "ppruiz@gmail.com": "Pepe tecnico Alumno",
    "pubmasmadera@hotmail.com": "Francisco Bonilla Alumno",
    "quiten_4@hotmail.com": "Quique pequeño alumno",
    "rafaeslir@gmail.com": "Rafa Escudero Alumno",
    "rebecamarin129@gmail.com": "galaxyxfan",
    "rigama72@hotmail.com": "Ricardo Alumno",
    "rociom.espejel@gmail.com": "Rocio Espejel Alumna",
    "rodricesar.kaz@hotmail.com": "Rodri Cesar Alumno",
    "runtothesousa@hotmail.com": "Jesus Sousa Alumno",
    "rupato87@hotmail.com": "Ruben Alumno",
    "ruzmelin@gmail.com": "Fran Ruz Alumno",
    "salsmy@hotmail.com": "Jose Manuel Diaz Alumno",
    "samuelmerino1@yahoo.es": "Samuel Alumno",
    "sergiorm1997@gmail.com": "Sergio Ruiz Alumno",
    "shu_jose_ay@hotmail.com": "Jose Antonio pareja Alumno",
    "soniavilchez2004@gmail.com": "Sonia Alumna",
    "sparatrapo@arquired.es": "Manuel Calvo Alumno",
    "suarezpaco@gmail.com": "Paco Suarez Alumno",
    "susana.casado.cano@gmail.com": "Susana Alumna",
    "tboiden@hotmail.com": "Esteban Alumno",
    "tboidenguitar@hotmail.com": "Esteban Alumno",
    "telomerase_bubbles@ymail.com": "Mehdy Alumno",
    "tirocrhon@gmail.com": "Jesus Gallardo Alumno",
    "tronco41@gmail.com": "Pepe Cordero Alumno",
    "viabellan@gmail.com": "Vicente Abellan Alumno",
    "vicengordillo@hotmail.com": "Vicente Alumno",
    "viktarrako@gmail.com": "Victor Rdz Alumno",
    "villa@us.es": "Rafa Villa Alumno",
    "wancho06@gmail.com": "Alejandro Rodriguez Alumno",
    "xavilens@gmail.com": "Xisco Alumno",
    "xenxu-sevillano@hotmail.com": "Xenxu Carlos Alumno",
    "zarpapatan@gmail.com": "Ian Revert Alumno",
}
